overrides:
  ansi-regex: ^6.3.0
  minimist: ^1.2.8
  "@wolfstar/http-framework": ^4.0.1

allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  prisma: true

dedupePeers: true

shellEmulator: true

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - "@wolfstar/plugin-i18next@2.0.3"
  - "@wolfstar/shared-http-pieces@2.0.2"

minimumReleaseAgeExcludePrune: true

shamefullyHoist: true

hoistPattern:
  - "*prisma*"

ignoreWorkspaceRootCheck: true
