// This file is automatically generated, do not edit it.
/* eslint-disable */
/* oxlint-disable */
// oxfmt-ignore
// prettier-ignore
import "i18next";

// oxfmt-ignore
// prettier-ignore
declare module "i18next" {
  interface CustomTypeOptions {
    resources: {
      "commands/setup": {
        name: "setup";
        description: "Open the interactive setup menu for this server.";
        menu: {
          placeholder: "Choose what you want to configure";
          close: "Close setup";
          options: {
            overview: {
              label: "Overview";
              description: "View the setup status";
            };
            add: {
              label: "Add a notification";
              description: "Subscribe to a Twitch streamer";
            };
            manage: {
              label: "Manage notifications";
              description: "Review, remove, or reset subscriptions";
            };
            test: {
              label: "Test notifications";
              description: "Verify the real delivery path";
            };
          };
        };
        modal: {
          title: "Add a Twitch notification";
          streamer: {
            label: "Streamer";
            placeholder: "e.g. shroud";
          };
          channel: {
            label: "Notification channel";
          };
          type: {
            label: "Notify when";
            online: "Stream goes online";
            offline: "Stream goes offline";
          };
          message: {
            label: "Custom message (optional)";
            placeholder: "Required for offline notifications";
          };
        };
        manage: {
          selectPlaceholder: "Select one or more notifications";
          removeButton: "Remove selected";
          resetButton: "Reset all";
          resetConfirmButton: "Confirm reset all";
          empty: "No notifications configured yet.";
          removeSuccess_one: "Removed {{count}} notification.";
          removeSuccess_other: "Removed {{count}} notifications.";
        };
        test: {
          selectPlaceholder: "Select a notification to test";
          empty: "No notifications configured yet.";
        };
        pages: {
          overview: "{{notice}}## Staryl setup\nConfigure Twitch notifications for this server from one place.\n**Current notifications:** {{count}}\nUse the menu below to add, manage, or test a notification.";
          add: "{{notice}}## Add a Twitch notification\nPress **Add notification** below and fill in:\n- the **streamer** to follow;\n- the Discord **channel** that receives the notification;\n- whether to notify when the stream goes **online** or **offline**;\n- an optional custom message (required for offline notifications).";
          manage_one: "{{notice}}## Manage Twitch notifications\nThis server currently has **{{count}}** configured notification.\nSelect one or more below to remove them, or reset everything.";
          manage_other: "{{notice}}## Manage Twitch notifications\nThis server currently has **{{count}}** configured notifications.\nSelect one or more below to remove them, or reset everything.";
          test: "{{notice}}## Test a notification\nSelect a notification below to send a preview through the same delivery path used by real Twitch events, so you can verify the channel and bot permissions.";
        };
        closed: "## Setup closed\nRun `/setup` whenever you need it again.";
        errors: {
          invalid: "This setup menu is invalid. Run `/setup` to open a new one.";
          ownerOnly: "Only the administrator who opened this setup menu can use it.";
          permissionRevoked: "You no longer have Administrator permission in this server. Run `/setup` again once it's restored.";
          actionUnavailable: "This setup action is no longer available. Run `/setup` again.";
          sectionUnavailable: "That setup section is not available.";
        };
      };
      "commands/subscriptions": {
        name: "subscriptions";
        description: "Manage the notification subscriptions for your server.";
      };
      "commands/twitch": {
        name: "twitch";
        description: "Manage the Twitch stream notification subscriptions.";
        addName: "add";
        addDescription: "Add a new Twitch subscription for a streamer.";
        removeName: "remove";
        removeDescription: "Remove a Twitch subscription for a streamer.";
        testName: "test";
        testDescription: "Send a test notification to check that an existing subscription works.";
        resetName: "reset";
        resetDescription: "Remove all Twitch subscriptions from this server.";
        showName: "show";
        showDescription: "Show all Twitch subscriptions for this server.";
        optionsStreamerName: "streamer";
        optionsStreamerDescription: "The Twitch streamer to subscribe to.";
        optionsChannelName: "channel";
        optionsChannelDescription: "The Discord channel to post notifications in.";
        optionsTypeName: "type";
        optionsTypeDescription: "Whether to notify when the streamer goes live or offline.";
        optionsMessageName: "message";
        optionsMessageDescription: "Custom message to include in the notification.";
        optionsTypeChoiceOnline: "Stream Online";
        optionsTypeChoiceOffline: "Stream Offline";
        streamerNotFound: "{{REDCROSS}} Sorry, I could not find the streamer. Are you sure you wrote their name correctly?";
        statusValues: ["online", "offline"];
        invalidStatus: '{{REDCROSS}} Woah there! I expected "online" or "offline", but I cannot understand what you gave me instead.';
        addDuplicated: "{{REDCROSS}} You're already subscribed to that streamer in this channel for that status.";
        addSuccessOffline: "{{GREENTICK}} Success! Whenever {{name}} goes offline, I will post a new message in {{channel}}.";
        addSuccessLive: "{{GREENTICK}} Success! Whenever {{name}} goes live, I will post a new message in {{channel}}.";
        addMessageForOfflineRequired: "{{REDCROSS}} I'm sorry but it is required to provide a message when making an offline subscription.";
        addFailedTwitch: "{{REDCROSS}} I could not create the subscription on Twitch's side. If this keeps happening, ask the bot administrator to check that `TWITCH_CLIENT_ID`, `TWITCH_CLIENT_SECRET`, `TWITCH_EVENT_SUB_SECRET`, and `TWITCH_EVENT_SUB_CALLBACK` are configured.";
        addFailedDatabase: "{{REDCROSS}} I could not save the subscription. Please try again later.";
        removeFailed: "{{REDCROSS}} I could not remove the subscription. Please try again later.";
        resetFailed: "{{REDCROSS}} I could not remove the subscriptions. Please try again later.";
        testSuccess: "{{GREENTICK}} Sent! Check {{channel}} — that is exactly what the notification will look like.";
        testFailed: "{{REDCROSS}} I could not read the subscriptions. Please try again later.";
        testFailedGuild: "{{REDCROSS}} I could not read this server. Please try again later.";
        testFailedChannel: "{{REDCROSS}} I can no longer see {{channel}}. Was it deleted, or did I lose access to it?";
        testFailedPermissions: "{{REDCROSS}} I cannot post in {{channel}}. I need the **View Channel**, **Send Messages** and **Embed Links** permissions there. This is why the notifications are not arriving.";
        testFailedSend: "{{REDCROSS}} Discord rejected the message for {{channel}}. Check my permissions there and try again.";
        testMissingMessage: "{{REDCROSS}} This offline subscription has no message saved, so there is nothing to send. Remove it and add it again with a message.";
        noSubscriptions: "{{REDCROSS}} I'm sorry but you are not subscribed to any streamers, mission abort!";
        removeStreamerNotSubscribed: "{{REDCROSS}} I'm sorry, you cannot unsubscribe from {{streamer}} because you are not subscribed to them.";
        removeNotToProvidedChannel: "{{REDCROSS}} I'm sorry; while you're subscribed to this streamer and streaming status, their subscription is not posted to {{channel}}.";
        removeStreamerStatusNotMatch: '{{REDCROSS}} I\'m sorry, but it looks like you\'re not getting {{status}} notifications for {{streamer}}. We support "online" and "offline" notifications.';
        removeSuccessOffline: "{{GREENTICK}} Success! I will no longer post messages to {{channel}} whenever {{name}} goes offline.";
        removeSuccessLive: "{{GREENTICK}} Success! I will no longer post messages to {{channel}} whenever {{name}} goes live.";
        resetSuccess_one: "{{GREENTICK}} Success! {{count}} subscription has been removed from this server.";
        resetSuccess_other: "{{GREENTICK}} Success! {{count}} subscriptions have been removed from this server.";
        showStreamerNotSubscribed: "{{REDCROSS}} You wanted to see all subscriptions from this streamer, but there are none!";
        showStatus: {
          live: "Live";
          offline: "Offline";
        };
        showUnknownUser: "Unknown";
        showEmbedTitle: "Twitch Subscriptions";
      };
      errors: {
        genericUnknownChannel: "I'm sorry, I tried to perform an action for a channel unknown to Discord and failed, this error has been reported to the developers.";
        genericUnknownGuild: "I'm sorry, I tried to perform an action for a server unknown to Discord and failed, this error has been reported to the developers.";
        genericUnknownMember: "I'm sorry, I tried to perform an action for a member unknown to Discord and failed, this error has been reported to the developers.";
        genericUnknownMessage: "I'm sorry, I tried to perform an action for a message unknown to Discord and failed, this error has been reported to the developers.";
        genericUnknownRole: "I'm sorry, I tried to perform an action for a role unknown to Discord and failed, this error has been reported to the developers.";
        genericMissingAccess: "I'm sorry, I tried to perform an action for a resource without the necessary permissions and failed, this error has been reported to the developers.";
        genericDiscordInternalServerError: "Oops, Discord broke itself, please try again later.";
        genericDiscordGateway: "Oops, the network is struggling to communicate with Discord, please try again later.";
        genericDiscordUnavailable: "Oops, Discord is currently unavailable, please try again later.";
        unexpectedIssue: "An unexpected error popped up! Safely aborting this command...";
        discordAbortError: "The request was aborted. Please try again later.";
      };
      "events/twitch": {
        embedDescription: "{{userName}} is now live!";
        embedDescriptionWithGame: "{{userName}} is now live - Streaming {{gameName}}!";
        offlinePostfix: "Staryl Twitch Notifications";
        testNotice: "🧪 **Test notification** — this is a preview requested by a server administrator, not a real stream update.";
        testPlaceholderTitle: "Test notification";
      };
      globals: {
        default: "{{key}} has not been localized for en-US yet.";
        defaultLanguage: "Default Language";
        no: "No";
        none: "None";
        unknown: "unknown";
        yes: "Yes";
        durationValue: "{{value, duration}}";
        numberValue: "{{value, number}}";
        numberCompactValue: "{{value, numberCompact}}";
        dateTimeValue: "{{value, dateTime}}";
        humanDateTimeValue: "{{value, humanDateTime}}";
        andListValue: "{{value, list(conjunction)}}";
        orListValue: "{{value, orList}}";
        dateFormat: "MM/DD/YYYY";
        dateFormatExplanation: "Month/Day/Year";
        back: "Back";
        stop: "Stop";
        set: "Set";
        remove: "Remove";
        reset: "Reset";
        value: "Value";
        cancel: "Cancel";
      };
    } & CustomResources;
  }

  interface CustomResources {}
}
