name: ci
on:
  pull_request:
    branches:
      - main
  #      - release
  push:
    branches:
      - main
  merge_group:
    branches:
      - main

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: 🔠 Lint project
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: lts/*

      - uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6.0.5e1c8eafbd745f64b1ef30a7d7ed7965034c486c
        name: 🟧 Install pnpm

      - name: 📦 Install dependencies (root only, no scripts)
        run: pnpm install --filter . --ignore-scripts

      - name: 🔠 Lint project
        run: pnpm lint

  build:
    name: � Build project
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: lts/*

      - uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6.0.5e1c8eafbd745f64b1ef30a7d7ed7965034c486c
        name: 🟧 Install pnpm

      - name: 📦 Install dependencies (root only, no scripts)
        run: pnpm install --filter . --ignore-scripts

      - name: � Build project
        run: pnpm build
